### ISSUE TITLE
Cannot use 'in' operator to search for 'undefined' in test_ci_cd

### ISSUE THREAD

**Issue by codeace** [galvez/yamlful#4]
` FATAL  Cannot use 'in' operator to search for 'undefined' in test_ci_cd                                                                                                                                                       14:17:54

  at generateMethod (node_modules/yamlful/index.js:47:12)
  at Array.map (<anonymous>)
  at yamlfu (node_modules/yamlful/index.js:91:36)
  at ModuleContainer.module.exports (node_modules/yamlful-nuxt/index.js:21:21)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:190:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1790:43)
`

**Comment by galvez** [comment]
Strange -- would have to look at a sample repository with your attempt.
